### ISSUE TITLE
It seems that the "prepare" files for the COCO dataset annotations are missing

### ISSUE THREAD

**Issue by KarlLi5** [mlpc-ucsd/MasQCLIP#1]
Hello, how can I obtain the two files "datasets/coco/annotations/ov_split_48_17/instances_train2017_seen48.json" and "datasets/coco/annotations/ov_split_48_17/instances_val2017_instances65.json"?

**Comment by tyxiong23** [comment]
Hi, thanks for your interest in our work. I have updated the script for splitting COCO dataset in [`datasets`](https://github.com/mlpc-ucsd/MasQCLIP/blob/main/datasets/prepare_coco_ovsplit.py). Run the script under `datasets` directory. You may also download the split dataset from this [link](https://drive.google.com/drive/folders/1ludEA33faUaROF1OPzl6SMnIckcldl1Q?usp=sharing).
