### ISSUE TITLE
Why do you remove RMA in MasQCLIP?

### ISSUE THREAD

**Issue by yxchng** [mlpc-ucsd/MasQCLIP#3]
Is it not useful when MasQ-Tuning is used?

**Comment by xuxalan** [comment]
Thanks for your interest. MasQ-Tuning and RMA (in [MaskCLIP](https://arxiv.org/abs/2208.08984)) play a similar role, which is to adapt the image-level CLIP model for segmentation tasks. As we have mentioned in the paper, MasQ-Tuning achieves better performance and is more parameter-efficient than RMA, so we remove RMA. But we do not experiment with combining these two together.
