### ISSUE TITLE
Why perform distillation instead of directly using the teacher model for mask proposals?

### ISSUE THREAD

**Issue by yxchng** [mlpc-ucsd/MasQCLIP#5]
Does using the teacher model directly perform worse? I am not quite sure why distillation is needed here. Can you kindly clarify? Thanks.

**Comment by tyxiong23** [comment]
Since the teacher model is only trained on base classes, it is biased toward base classes and lacks generalization ability to novel classes (that are only seen during testing). Our distillation method is to improve model performance on novel classes that are not labeled during training.

**Comment by yxchng** [comment]
@tyxiong23 Are ablations done to verify this? What is the performance gap between directly using teacher and using the student? Do you think "distillation improves performance on novel classes" is generalizable, i.e. take any other open-vocab model, perform distillation on it and performance on novel classes will improve?

**Comment by tyxiong23** [comment]
We did ablations to verify that. You may refer to page 7 of our original paper for more details.

Personally, I think distillation is generalizable, since it adds more supervision and makes the training set more "unbiased".
